---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres
    author: rajkumar
spec:
  replicas: 2
  selector:
    matchLabels:
      name: postgres
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres
    spec:
      containers:
        - name: mypostgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: Sunny@1406
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb

